version: '3.8'
services:
  api-service:
    build:
      context: ./api
    ports:
      - "5212:8080"
  ui-app:
    build:
      context: ./ui/InsightAdvisor
    ports:
      - "4200:4000"
    depends_on:
      - api-service